Prohibir a aleix el acceso
Cadiducho/CadiBot pull request #13
Opened 2022-11-19 22:35 UTC by zugazagoitia

2022-11-19 22:40 UTC, zugazagoitia commented
Altamente necesario.

2022-11-20 12:38 UTC, Eschiclers commented on src/main/java/com/cadiducho/bot/modules/desmotivaciones/cmds/DesmotivacionCMD.java
> +		aliases = {"/desmotivacion", "/desmotivaciones", "/desmotiva"},
```sugestion
        aliases = {"/desmotivacion", "/desmotivaciones", "/desmotiva"},
```

2022-11-20 12:43 UTC, Eschiclers requested changes
No me toques los cojones que te meto un navajazo que te corto el ADN

2022-11-20 12:43 UTC, Eschiclers commented on src/main/java/com/cadiducho/bot/modules/desmotivaciones/cmds/DesmotivacionCMD.java
> +		aliases = {"/desmotivacion", "/desmotivaciones", "/desmotiva"},
```suggestion
        aliases = {"/desmotivacion", "/desmotivaciones", "/desmotiva"},
```

2022-11-20 12:43 UTC, Eschiclers commented on src/main/java/com/cadiducho/bot/modules/desmotivaciones/cmds/DesmotivacionCMD.java
> +		description = "Obtiene un cartel aleatorio de desmotivaciones.es"
```suggestion
        description = "Obtiene un cartel aleatorio de desmotivaciones.es"
```

2022-11-20 12:43 UTC, Eschiclers commented on src/main/java/com/cadiducho/bot/modules/desmotivaciones/cmds/DesmotivacionCMD.java
> +	}
```suggestion
    }
```

2022-11-20 12:43 UTC, Eschiclers commented on src/main/java/com/cadiducho/bot/modules/desmotivaciones/cmds/DesmotivacionCMD.java
> +	@Override
```suggestion
    @Override
```

2022-11-20 12:43 UTC, Eschiclers commented on src/main/java/com/cadiducho/bot/modules/desmotivaciones/cmds/DesmotivacionCMD.java
> +	public void execute(Chat chat, User user, CommandContext commandContext, Integer integer, Message message, Instant instant) throws TelegramException {
```suggestion
    public void execute(Chat chat, User user, CommandContext commandContext, Integer integer, Message message, Instant instant) throws TelegramException {
```

2022-11-20 12:43 UTC, Eschiclers commented on src/main/java/com/cadiducho/bot/modules/desmotivaciones/cmds/DesmotivacionCMD.java
> +		if (user.getId() != 124618317L) {
```suggestion
```

2022-11-20 12:43 UTC, Eschiclers commented on src/main/java/com/cadiducho/bot/modules/desmotivaciones/cmds/DesmotivacionCMD.java
> +			String cartel = DesmotivacionesModule.getAPost();
```suggestion
        String cartel = DesmotivacionesModule.getAPost();
```

2022-11-20 12:43 UTC, Eschiclers commented on src/main/java/com/cadiducho/bot/modules/desmotivaciones/cmds/DesmotivacionCMD.java
>          }
```suggestion
```

2023-05-01 13:09 UTC, closed without merging